<?php
    use Magento\Backend\Block\Template;
    /** @var Template $block */
    $data = $block->getData('testimonial')
?>

<form action="<?= $block->getUrl('testimonial_admin/testimonial/update', ['_secure' => true]) ?>"
      method="post"
>
    <input type="hidden" value="<?= $data['id'] ?>" name="id">
    <p>Id Customer</p>
    <input type="text" required value="<?= $data['id_customer'] ?>" name="id_customer">
    <p>Content</p>
    <textarea name="content" rows="10" cols="50">
        <?= $data['content'] ?>
    </textarea>
    <p>Rating</p>
    <select name="rating">
        <?php
        for ($i=1; $i<=5; $i++) {
            ?>
            <option value="<?= $i ?>" <?php if ($i == $data['rating']) {echo 'selected';}?>><?= $i ?> sao</option>
            <?php
        }
        ?>
    </select>
    <p>status</p>
    <input type="checkbox" <?php if ($data['status'] == 1) {echo 'checked';} ?> name="status">
    <p>last updated at : <?= $data['update_at'] ?></p>
    <p></p>
    <input type="submit" value="update">
</form>
