<?php
    use Magento\Framework\View\Element\Template;
    /** @var Template $block */
?>

<h1>Create new testimonial</h1>
<form method="POST"
      action="<?= $block->getUrl('testimonial/testimonial/insert') ?>"
>
    <p>How do you thing?</p>
    <label>
        <textarea name="testimonial_content"></textarea>
    </label>
    <p>How many star for this?</p>
    <label>
        <select name="rating">
            <?php
                for ($i=1; $i<=5; $i++) {
                    ?>
                    <option value="<?= $i ?>"><?= $i ?> Sao</option>
            <?php
                }
            ?>
        </select>
    </label>
    <p> </p>
    <input type="submit" value="submit">
</form>
